### ISSUE TITLE
Device unable to obtain IP address and  http failure response when not connected to the internet 

### ISSUE THREAD

**Issue by LURION-444** [google/testrun#537] opened 2024-06-22 05:12 UTC
Device is not able to obtain IP address & http failure response at http://localhost:8080/ 

Recreate the issue :  (when connected to wifi, when not connected to wifi, server throws an error " http failure response, internal error : 505)
1. Run testrun
2. Connect device
3. Failed to obtain ip

Below attached Debug data in txt file.
[Terminal Debug.txt](https://github.com/user-attachments/files/15935364/Terminal.Debug.txt)

**Comment by jhughesbiot** [comment] 2024-06-24 19:06
From the output you provided, here is what I am seeing:

1. It appears that your system is not connected to the internet as it can't resolve an outbound connection using DNS to resolve the latest version from github.  This will prevent Testrun from providing you information about more recent updates being available as well as giving incomplete results for the DNS and TLS tests which both require internet access.

`Jun 21 19:21:12 api      DEBUG   HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/google/testrun/releases/latest (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x776e55e17400>: Failed to resolve `

2. The device not receiving an IP is likely due to the device being powered on before the testing started.  The log appears to show the device was detected within 9 seconds of the network being ready which is common for already powered on devices.  Unless you do indeed have a device that boots up in less than 10 seconds.  If that is the case, I would recommend confirming the device is configured for DHCP. 
```
Jun 21 19:21:53 test_run INFO    Waiting for devices on the network...
Jun 21 19:22:02 net_orc  DEBUG   Discovered device cc:d3:1e:82:0a:31. Waiting for device to obtain IP
```

 You can also connect a separate computer to the system using an unmanaged switch and start testrun in network only mode to observe the devices behavior directly:

`sudo testrun --no-ui --net-only`

In network only mode, you should be able to connect both a test computer and the device to the same virtual network used during testing and manually verify any issues with the device resolving an IP address.

3. I do not see the HTTP 505 error anywhere in the log so this may be isolated to the browser.  Can you provide screen shots or console logs from the browser showing the error and a description of what it was you were doing when the error happened?

**Comment by LURION-444** [comment] 2024-06-26 08:40
Hi,
Thank you for your response. I will follow your troubleshooting steps and re-upload new log files in sometime.

The devices which require qualification does not support DHCP as mentioned by the manufacturer. 
Further to this, the device label specifies an ip address as  " 10.84.10.49 " . 
So please share your inputs on how to qualify such devices.

**Comment by jhughesbiot** [comment] 2024-06-26 14:42
Unfortunately, DHCP is one of the core requirements for device qualification.  If the device doesn't support DHCP, it can't be qualified.  You can see the full list of DHCP related tests that are required [here](https://github.com/google/testrun/tree/main/modules/test/conn)

**Comment by jboddey** [comment] 2024-06-28 08:47
@LURION-444 I will close this issue now. If you have any further questions regarding qualification please get in touch with anniappan@google.com

**Closed by jboddey** 2024-06-28 08:47 UTC
