### ISSUE TITLE
Blank testing complete modal window appears if testrun is launched again in another tab

### ISSUE THREAD

**Issue by duncangreene** [google/testrun#891] opened 2024-10-16 16:11 UTC
**Describe the bug**
A blank 'testing has just finished' modal window appears if testrun is launched again in another tab after a test has finished.

![Image](https://github.com/user-attachments/assets/23e17642-a111-463e-a45e-10a2c7f918a9)

**To Reproduce**
1. Web browse to Testrun from an external machine (e.g. http://192.168.0.67:8080/).
2. Run a test and let it complete. Cancel out of the report download modal window once the test has completed.
3. Web browse to Testrun from the same external machine but in a new tab (e.g. http://192.168.0.67:8080/).
4. Screenshot as above is shown.

**Expected behavior**
The blank modal should not appear.

**Environment (please provide the following information about your setup):**
- OS: Ubuntu
- Version 24.04.1
- Testrun 2.0

**Comment by jboddey** [comment] 2024-10-18 08:34
Thanks for the bug report. We will take a look at this.

**Comment by KrystsinaT** [comment] 2024-10-18 08:51
@jboddey the issue was reported on the FE side with id 374249859

**Comment by jboddey** [comment] 2024-10-18 12:52
This is unusual as currently there is a known bug that prevents users from using Testrun from an external PC as the UI tries to connect to the MQTT broker on localhost instead of the actual machine running Testrun. I was not able to reproduce

**Comment by jboddey** [comment] 2024-10-21 10:20
This has been fixed in PR #906 and will be released in v2.1

**Closed by jboddey** 2024-10-21 10:20 UTC
Labels: bug
